### ISSUE TITLE
"persistentSV_logoString" error in package ...

### ISSUE THREAD

**Issue by nhudinh2103** [crysehillmes/PersistentSearchView#5]
I try to add this attribute to my layout xml but it displays an error.
I use your repo through depedencies in android studio.

**Comment by crysehillmes** [comment]
@nhudinh2103 Sorry for this problem, I updated the README.md but forgot to update package in repo. I'll upload a new version soon.

**Comment by nhudinh2103** [comment]
@crysehillmes Thanks for your response. Waiting for update :d

**Comment by crysehillmes** [comment]
@nhudinh2103 Uploaded to jcenter now.
